//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vimseproject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class billinginfo
    {
        public int Customer_ID { get; set; }
        public string Customer_Name { get; set; }
        public Nullable<int> Policy_ID { get; set; }
        public string Customer_Add_Prove { get; set; }
        public Nullable<int> Customer_Phone { get; set; }
        public Nullable<int> Bill_ID { get; set; }
        public string Vehicle_Name { get; set; }
        public string Vehicle_Model { get; set; }
        public Nullable<int> Vehicle_Rate { get; set; }
        public string Vehicle_Body_Number { get; set; }
        public string Vehicle_Engine_Number { get; set; }
        public string Date { get; set; }
        public Nullable<int> Amount { get; set; }
    }
}
