//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vimseproject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class claim_datails
    {
        public int Claim_ID { get; set; }
        public Nullable<int> Policy_ID { get; set; }
        public string Policy_Start_Date { get; set; }
        public string Policy_End_Date { get; set; }
        public string Customer_Name { get; set; }
        public string Place_Of_Accident { get; set; }
        public string Date_Of_Accident { get; set; }
        public Nullable<int> Insured_Amount { get; set; }
        public Nullable<int> Claimable_Amount { get; set; }
    }
}
