//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vimseproject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class company_expenses
    {
        public int Expence_ID { get; set; }
        public string Date_of_Expence { get; set; }
        public string Type_of_Expence { get; set; }
        public string Amount_of_Expence { get; set; }
    }
}
