//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vimseproject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vehicleinfo
    {
        public int Vehicle_ID { get; set; }
        public string Vehicle_Name { get; set; }
        public string Vehicles_Owner_Address { get; set; }
        public string Vehicle_Model { get; set; }
        public string Vehicle_Version { get; set; }
        public Nullable<int> Vehicle_Rate { get; set; }
        public string Vehicle_Body_Number { get; set; }
        public string Vehicle_Engine_Number { get; set; }
        public Nullable<int> Vehicle_Number { get; set; }
    }
}
