//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vimseproject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class vimsEntities : DbContext
    {
        public vimsEntities()
            : base("name=vimsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<billinginfo> billinginfoes { get; set; }
        public virtual DbSet<claim_datails> claim_datails { get; set; }
        public virtual DbSet<company_expenses> company_expenses { get; set; }
        public virtual DbSet<customer_policy_records> customer_policy_records { get; set; }
        public virtual DbSet<customerinfo> customerinfoes { get; set; }
        public virtual DbSet<estimate> estimates { get; set; }
        public virtual DbSet<userinfo> userinfoes { get; set; }
        public virtual DbSet<vehicleinfo> vehicleinfoes { get; set; }
    }
}
